#!/usr/bin/env bash
# This script will print numbers 1-100 and change multiples of 3 and 5

x=1

while [ $x -le 100 ]
do
	if [ $(( x % 15 )) -eq 0 ]; then
		echo FizzBuzz
	elif [ $(( x % 3 )) -eq 0 ]; then
		echo Fizz
	elif [ $(( x % 5 )) -eq 0 ]; then
		echo Buzz
	else
		echo $x
	fi

	(( x++ ))
done
