#!/usr/bin/env bash
# display info head in /etc/passwd but only username, user id, and home directory path for the user

file="/etc/passwd"

while IFS= read -r line
do
	echo "$line" | cut -d':' --fields=1,3,6	

done < "$file"
