#!/usr/bin/env bash
# run a loop upto 20 times with if/elif/else

x=1

while [ $x -le 20 ]
do

if [ $x = 4 ]; then
	echo "bad luck for China"
elif [ $x = 9 ]; then
	echo "bad luck for Japan"
elif [ $x = 17 ]; then
	echo "bad luck for Italy"
else
	echo "$x"
fi
(( x++ ))
done
