#!/usr/bin/env bash
# Print information on a file if it exists

file="school"

if [ -e $file ]; then #check if file exists
	echo school file exists

	# display info on file
	if [ -s $file ]; then #check file size is >0
		echo school file is not empty
	else
		echo school file is empty
	fi
	if [ -f $file ]; then #check if file is regular
		echo school is a regular file
	fi
else
	#file does not exist
	echo school file does not exist
fi
